const ActionTypes = {
  USER_SIGNUP_LOADING: "USER_SIGNUP_LOADING",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAIL: "USER_SIGNUP_FAIL",

  //login
  USER_LOGIN_LOADING: "USER_LOGIN_LOADING",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",

  //ADD PAYMENT
  ADD_PAYMENT_LOADING: "ADD_PAYMENT_LOADING",
  ADD_PAYMENT_SUCCESS: "ADD_PAYMENT_SUCCESS",
  ADD_PAYMENT_FAIL: "ADD_PAYMENT_FAIL",
  ADD_PAYMENT_EMPTY: "ADD_PAYMENT_EMPTY",

  //EDIT PAYMENT
  EDIT_PAYMENT_LOADING: "EDIT_PAYMENT_LOADING",
  EDIT_PAYMENT_SUCCESS: "EDIT_PAYMENT_SUCCESS",
  EDIT_PAYMENT_FAIL: "EDIT_PAYMENT_FAIL",
  EDIT_PAYMENT_EMPTY: "EDIT_PAYMENT_EMPTY",

  //GET PAYMENT
  GET_PAYMENT_LOADING: "GET_PAYMENT_LOADING",
  GET_PAYMENT_SUCCESS: "GET_PAYMENT_SUCCESS",
  GET_PAYMENT_FAIL: "GET_PAYMENT_FAIL",

  //DELET PAYMENT
  DELETE_PAYMENT_LOADING: "DELETE_PAYMENT_LOADING",
  DELETE_PAYMENT_SUCCESS: "DELETE_PAYMENT_SUCCESS",
  DELETE_PAYMENT_FAIL: "DELETE_PAYMENT_FAIL",

  //MARK AS PAID PAYMENT
  MARK_AS_PAID_LOADING: "MARK_AS_PAID_LOADING",
  MARK_AS_PAID_SUCCESS: "MARK_AS_PAID_SUCCESS",
  MARK_AS_PAID_FAIL: "MARK_AS_PAID_FAIL",

  //GET NOTIFICATION
  GET_NOTIFICATION_LOADING: "GET_NOTIFICATION_LOADING",
  GET_NOTIFICATION_SUCCESS: "GET_NOTIFICATION_SUCCESS",
  GET_NOTIFICATION_FAIL: "GET_NOTIFICATION_FAIL",

  //GET NOTIFICATION
  MARK_ALL_NOTIFICATION_LOADING: "MARK_ALL_NOTIFICATION_LOADING",
  MARK_ALL_NOTIFICATION_SUCCESS: "MARK_ALL_NOTIFICATION_SUCCESS",
  MARK_ALL_NOTIFICATION_FAIL: "MARK_ALL_NOTIFICATION_FAIL",

  //COUNT NOTIFICATION
  COUNT_NOTIFICATION_LOADING: "COUNT_NOTIFICATION_LOADING",
  COUNT_NOTIFICATION_SUCCESS: "COUNT_NOTIFICATION_SUCCESS",
  COUNT_NOTIFICATION_FAIL: "COUNT_NOTIFICATION_FAIL",
  NOTIFICATION_COUNT_ZERO: "NOTIFICATION_COUNT_ZERO",

  ///DEVICE ID
  UPDATE_DEVICEID_REQUEST: "UPDATE_DEVICEID_REQUEST",
  UPDATE_DEVICEID_SUCCESS: "UPDATE_DEVICEID_SUCCESS",
  UPDATE_DEVICEID_FAIL: "UPDATE_DEVICEID_FAIL",
};

export default ActionTypes;
